version: 2
jobs:
  build:
    docker:
      - image: yuanz271/texlive
    steps:
      - checkout
      - run: sh build.sh
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: sh upload.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build