version: 2
jobs:
  build:
    docker:
      - image: yuanz271/texlive
    steps:
      - run: apt-get -q -y update && apt-get -q -y install git make curl wget xzdec
      - run: apt-get -q -y install fonts-ebgaramond fonts-font-awesome
      # - run: mkdir -p /root/texmf
      # - run: tlmgr init-usertree && tlmgr option repository ftp://tug.org/historic/systems/texlive/2017/tlnet-final && tlmgr install fontawesome
      - checkout
      - run: make
      - deploy: 
          command: sh upload.sh